services:
  astro:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    container_name: astro_dev
    ports:
      - "4321:4321"
    volumes:
      - .:/app             # Sincroniza o código local com o container
      - /app/node_modules  # Evita que o node_modules local sobrescreva o do container
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0 # Garante que o Astro aceita conexões externas
